#!/usr/bin/env python
#
# logIMU for imu4gopigo3ros
#
# logs imu heading and rotation each time GoPiGo3 stops moving
#
# Assumes ROS IMU orientation for DI BN0055 Inertial Measurement Unit
#   ("chip side up", arrow head pointed left, horizontal mounting)
#
# Usage:
#   startIMU [-i]
#   logIMU &
#   (note process so can kill it later)
#
# Logs to ./imu.log
#
# 2021-10-08 10:43|[imulog.py.logCurrentIMU]heading:   349.4  rotation:     0.0 motion:     0.0 sec errors: 0  imulog started
# 2021-10-08 10:43|[imulog.py.logMotionStop]heading:   347.2  rotation:   357.8 motion:     5.6 sec errors: 0


"""
Documentation:
  Detects rotation, logs results at end of movement to imu.log
  End_time, duration,start_heading, end_heading, rotation
"""

from __future__ import print_function
from __future__ import division


import sys
import logging

import easygopigo3 # import the EasyGoPiGo3 class
import numpy as np
import datetime as dt
from math import pi

import time
from ros_safe_inertial_measurement_unit import SafeIMUSensor
import rosBNO055 as BNO055

DEBUG = True


# CONSTANTS
MOTION_NONE    = 0
MOTION_START   = 1
MOTION_MOVING  = 2
MOTION_STOP    = 3
MOTION_UNKNOWN = 4

# Port must be "AD1" or "AD2" to force software I2C that properly implements clock stretch
IMUPORT = "AD1"


# VARIABLES
motion_state = MOTION_UNKNOWN
strt_heading = 0
curr_heading = 0
delta_heading = 0
strt_time  = 0
stop_time  = 0
motion_sec  = 0
lst_heading = 999
zero_crossed = 0  # + CW  - CCW


# METHODS

# create logger
imuLog = logging.getLogger('imuLog')
imuLog.setLevel(logging.INFO)

loghandler = logging.FileHandler('./imu.log')

logformatter = logging.Formatter('%(asctime)s|[%(filename)s.%(funcName)s]%(message)s',"%Y-%m-%d %H:%M")
loghandler.setFormatter(logformatter)
imuLog.addHandler(loghandler)


# motionChange(egpg)
#
# reads imu, returns one of [MOTION_NONE, MOTION_START, MOTION_MOVING, MOTION_STOP, MOTION_UNKNOWN)
#
def motionChange(egpg):
    global motion_state, curr_heading, strt_heading, delta_heading, lst_heading, zero_crossed, strt_time, stop_time, motion_sec
    global MOTION_NONE, MOTION_START, MOTION_STOP, MOTION_MOVING, MOTION_UNKNOWN

    # list
    #   flags bit 0 -- motors are disabled due to low battery voltage
    #         bit 1 -- motors are not close to target or dps speed control
    #   power -- raw PWM power -100 to 100 percent
    #   encoder position
    #   dps -- speed in degrees per second
    motor_state_l = egpg.get_motor_status(egpg.MOTOR_LEFT)
    # print("motor_state_l: ", motor_state_l)

    motor_state_r = egpg.get_motor_status(egpg.MOTOR_RIGHT)
    # print("motor_state_r: ", motor_state_r)

    # Just before motors start moving, the dps value may be out of permitted range ( e.g. 6267 or -6276 )
    # Motors are not running (yet) - ignore
    if ((abs(motor_state_l[3]) < 1000) and (abs(motor_state_r[3]) < 1000)):
         motors_running = motor_state_l[3] | motor_state_r[3]
    else:
         motors_running = 0
    # print("motors_running: ", motors_running)
    # print("motion_state: ", motion_state)

    # print("left:{} right:{} running:{} state:{}".format(motor_state_l,motor_state_r,motors_running,motion_state))
    curr_heading = egpg.imu.safe_read_euler()[0]
    # print("curr_heading: {}".format(curr_heading))

    if (motion_state == MOTION_UNKNOWN):
        if motors_running:
            strt_time = time.time()
            strt_heading = curr_heading
            lst_heading = curr_heading
            zero_crossed = 0
            motion_state = MOTION_MOVING
        else:
            motion_state = MOTION_NONE
    elif (motion_state == MOTION_NONE):
        if motors_running:
            strt_time = time.time()
            strt_heading = curr_heading
            lst_heading = curr_heading
            zero_crossed = 0
            motion_state = MOTION_MOVING
    elif (motion_state == MOTION_MOVING):
        if (motors_running == 0):
            stop_time = time.time()
            # This is some tricky logic to account for crossing heading of zero, even multiple times
            if zero_crossed == 0:
                # zero not crossed (or crossed and returned)
                delta_heading = curr_heading - strt_heading
            else:
                # zero crossed (CW if positive, CCW if negative)
                # For case start 355 end 5:  1*360  - (355-5) so 360-350 = 10 deg
                # For case start 355 end 5 but also turned full circle getting there:  2*360 - (355-5) so 720-350=360+10=370
                # For case start 5 end 355:  -1*360 - (5-355) so -360+350 = -10 deg
                # For case start 5 end 355 but also turned full circle getting there:  -2*360 - (5-355) so -720+350=-360+ -10=-370
                delta_heading = (zero_crossed * 360.0) - ( strt_heading - curr_heading)
            motion_sec = stop_time - strt_time
            motion_state = MOTION_STOP
        else:  # still moving detect 0 crossing
            if (lst_heading > 350) and (curr_heading < 10):
                zero_crossed += 1
            elif (lst_heading < 10) and (curr_heading > 350):
                zero_crossed -= 1
            lst_heading = curr_heading
    elif (motion_state == MOTION_STOP):
        motion_state = MOTION_NONE
    return motion_state


def logMotion(egpg):
    global motion_state, curr_heading, strt_heading, delta_heading, zero_crossed, strt_time, stop_time, motion_sec
    print("motion_state: {}  HEADINGS  current: {}  start: {} zero_crossed: {} strt_time: {} motion_sec: {} ".format(motion_state,curr_heading,zero_crossed,strt_heading,stop_time,motion_sec))

def logMotionStop(egpg):
    global motion_state, curr_heading, strt_heading, delta_heading, zero_crossed, strt_time, stop_time, motion_sec

    rotate_deg = delta_heading
    strToLog = "heading: {:>7.1f}  rotation: {:> 7.1f} motion: {:> 7.1f} sec errors: {}".format(
                round(curr_heading,1), round(rotate_deg,1), round(motion_sec,1), egpg.imu.getExceptionCount())
    # print("{} {}".format(time.ctime(stop_time),strToLog))
    # print(strToLog)
    imuLog.info(strToLog)

def logCurrentIMU(egpg,comment=""):
    global curr_heading, motion_sec

    # Log current heading (probably just reset), with no rotation and no time in motion
    rotate_deg = 0
    motion_sec = 0

    # if comment passed, put space in front of it, otherwise no spaces written to log
    if (len(comment) > 0): comment = "  " + comment

    strToLog = "heading: {:>7.1f}  rotation: {:> 7.1f} motion: {:> 7.1f} sec errors: {}{}".format(
                round(curr_heading,1), round(rotate_deg,1), round(motion_sec,1), egpg.imu.getExceptionCount(), comment)
    # print("{} {}".format(time.ctime(stop_time),strToLog))
    # print(strToLog)
    imuLog.info(strToLog)


# MAIN
def main():
    global motion_state, curr_heading, strt_heading, delta_heading, zero_crossed, strt_time, stop_time, motion_sec

    try:
        egpg = easygopigo3.EasyGoPiGo3(use_mutex=True)
    except:
        strToLog = "Could not instantiate an EasyGoPiGo3"
        print(strToLog)
        exit(1)

    try:

        egpg.imu = SafeIMUSensor(port = IMUPORT, use_mutex = True, init = False)
        time.sleep(1.0)  # allow measurements to init
        curr_heading = egpg.imu.safe_read_euler()[0]
        strt_heading = curr_heading

        # Do Somthing in a Loop
        loopSleep = 0.05 # second (20 times / second)
        keepLooping = True

        logCurrentIMU(egpg,"imulog started")

        while keepLooping:
            if (motionChange(egpg) == MOTION_STOP):
                logMotionStop(egpg)
            else:
                pass
            time.sleep(loopSleep)


    except KeyboardInterrupt: # except the program gets interrupted by Ctrl+C on the keyboard.
       	    if (egpg != None): egpg.stop()           # stop motors
            print("\n*** Ctrl-C detected - Finishing up")
            time.sleep(1)
    if (egpg != None): egpg.stop()
    time.sleep(1)


if (__name__ == '__main__'):  main()
